### ISSUE TITLE
[Bug] - Website highlighting inconsistent

### ISSUE THREAD

**Issue by TFWol** [Yanorei32/GSI4D#13]
It looks like highlighting is sporadic.

![image](https://github.com/yanorei32/GSI4D/assets/9045213/700ea239-f489-4c28-b572-ba5d72584018)

![image](https://github.com/yanorei32/GSI4D/assets/9045213/f4e8001f-5df9-4eee-bd4f-4957c31b3eff)

**Comment by yanorei32** [comment]
OMG!
I tested that in some situations but it was not reproduced.
Does this bug occur only in some contexts, settings, or browsers?

![image](https://github.com/yanorei32/GSI4D/assets/11992915/c53dad74-bcd9-4f5c-91fb-26bfc518703e)
![image](https://github.com/yanorei32/GSI4D/assets/11992915/6eca9ddd-1a22-43e7-b050-f45ac42d8428)

**Comment by yanorei32** [comment]
I reproduced that in lazy-loaded content!
![image](https://github.com/yanorei32/GSI4D/assets/11992915/f3498fd9-de04-4318-8158-6c3e964d9cda)

**Comment by yanorei32** [comment]
Currently, this UserScript does not scan lazily loaded contents.
We should add a re-scan code for those.

**Comment by yanorei32** [comment]
I fixed that locally.
I publish a release in a few minutes!

**Comment by yanorei32** [comment]
I fixed that! nice catch!
If this problem still occurs in 1.5.10, please reopen this issue!

**Comment by TFWol** [comment]
I was surprised by the quick response!
It's happening less, I think, but still occurs.

I did a search with `site:youtube.com` to get:
![image](https://github.com/yanorei32/GSI4D/assets/9045213/5e5b035b-ab50-40ec-a983-6e1441e6d6f5)

**Comment by yanorei32** [comment]
oh, I'm sorry for the inconvenience.
This problem is the code crashes by hitting to element that has a thumbnail.

**Comment by yanorei32** [comment]
I added the code to the structure analysis.
It should be fixed in 1.6.10.
I'm sorry.

**Comment by TFWol** [comment]
That worked (as of v1.7.10) 👍
